# Generated by Django 5.2.15 on 2026-06-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='password',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='enrollment_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
