# Generated by Django 5.2.15 on 2026-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_voter_password_alter_voter_enrollment_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
