# Generated by Django 5.2.15 on 2026-06-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_electionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
