# Generated by Django 5.2.15 on 2026-06-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_electionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='password',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='username',
            field=models.CharField(default='12345', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='username',
            field=models.CharField(default='12345', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
