# Generated by Django 5.2.15 on 2026-06-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_candidate_password_candidate_username_voter_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='password',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='username',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='username',
        ),
        migrations.AddField(
            model_name='candidate',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.candidate'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='enrollment_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
