# Generated by Django 5.2.15 on 2026-06-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_delete_staff_remove_candidate_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='password',
            field=models.CharField(default='12345', max_length=50),
        ),
    ]
